[theme]

# Primary accent for interactive elements
primaryColor = '#ffffff'

# Background color for the main content area
backgroundColor = '#a04c9c'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#9711d0'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"